repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v0.9.4
  hooks:

  - id: trailing-whitespace
    entry: trailing-whitespace-fixer
    language: python
    types: [text]
  - id: end-of-file-fixer
  - id: double-quote-string-fixer
  - id: requirements-txt-fixer
  - id: check-merge-conflict
  - id: flake8
    args: [--ignore=E501, --max-complexity=5]
  - id: check-json
